<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class WarehouseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        
        DB::table('categories')->insert([
            [   
                'id'=>0,
                'title'=>"không xác định",
                'slug'=>'khong_xac_dinh',
                'status'=>'active',
                'is_parent'=>0

            ],
        ]);
        DB::table('setting_details')->insert([
            [   
                'company_name'=>"Tên công ty",
                'web_title'=>"Tên công ty",
                'phone'=>'0500363732',
                'address'=>'Ywang Buôn Ma Thuột, Đăk Lăk',
            ],
        ]);
       
        DB::table('themesettings')->insert([
            [   
                'title'=>"frontend_tp",
            ],
        ]);
        DB::table('roles')->insert([
            [   
                'alias'=>'admin',
                'title'=>"Quản trị viên",
                'status'=>'active',
            ],
            [   
                'alias'=>'manager',
                'title'=>"Quản lý",
                'status'=>'active',
            ],
            [   
                'alias'=>'vendor',
                'title'=>"Bán hàng",
                'status'=>'active',
            ],
            [   
                'alias'=>'customer',
                'title'=>"Khách hàng",
                'status'=>'active',
            ],
            [   
                'alias'=>'supplier',
                'title'=>"Nhà cung cấp",
                'status'=>'active',
            ],
            [   
                'alias'=>'supcustomer',
                'title'=>"Nhà cung cấp và khách hàng",
                'status'=>'active',
            ],
            [   
                'alias'=>'soft',
                'title'=>"soft",
                'status'=>'active',
            ],
        ]);
        DB::table('cmd_functions')->insert(
            [
                ["alias"=>"user_add","title"=>"Thêm người dùng","status"=>"active"],
                ["alias"=>"user_edit","title"=>"Điều chỉnh người dùng","status"=>"active"],
                ["alias"=>"user_list","title"=>"Xem người dùng","status"=>"active"],
                ["alias"=>"user_delete","title"=>"Xóa người dùng","status"=>"active"],
                ["alias"=>"ugroup_add","title"=>"Thêm nhóm người dùng","status"=>"active"],
                ["alias"=>"ugroup_edit","title"=>"Điều chỉnh nhóm người dùng","status"=>"active"],
                ["alias"=>"ugroup_list","title"=>"Xem nhóm người dùng","status"=>"active"],
                ["alias"=>"ugroup_delete","title"=>"Xóa nhóm người dùng","status"=>"active"],
                ["alias"=>"pw_add","title"=>"QL tài sản->kho bán hàng thêm","status"=>"active"],
                ["alias"=>"pw_edit","title"=>"Điều chỉnh QL tài sản->kho bán hàng","status"=>"active"],
                ["alias"=>"pw_list","title"=>"Xem QL tài sản->kho bán hàng","status"=>"active"],
                ["alias"=>"pw_delete","title"=>"Xóa QL tài sản->kho bán hàng","status"=>"active"],
                ["alias"=>"pm_add","title"=>"QL tài sản->kho bảo hành thêm","status"=>"active"],
                ["alias"=>"pm_edit","title"=>"Điều chỉnh QL tài sản->kho bảo hành","status"=>"active"],
                ["alias"=>"pm_list","title"=>"Xem QL tài sản->kho bảo hành","status"=>"active"],
                ["alias"=>"pm_delete","title"=>"Xóa QL tài sản->kho bảo hành","status"=>"active"],
                ["alias"=>"pd_add","title"=>"QL tài sản->kho hủy thêm","status"=>"active"],
                ["alias"=>"pd_edit","title"=>"Điều chỉnh QL tài sản->kho hủy","status"=>"active"],
                ["alias"=>"pd_list","title"=>"Xem QL tài sản->kho hủy","status"=>"active"],
                ["alias"=>"pd_delete","title"=>"Xóa QL tài sản->kho hủy","status"=>"active"],
                ["alias"=>"product_add","title"=>"Sản phẩm thêm","status"=>"active"],
                ["alias"=>"product_edit","title"=>"Điều chỉnh Sản phẩm","status"=>"active"],
                ["alias"=>"product_list","title"=>"Xem Sản phẩm","status"=>"active"],
                ["alias"=>"product_delete","title"=>"Xóa Sản phẩm","status"=>"active"],
                ["alias"=>"order_add","title"=>"đơn hàng thêm","status"=>"active"],
                ["alias"=>"order_edit","title"=>"Điều chỉnh đơn hàng","status"=>"active"],
                ["alias"=>"order_list","title"=>"Xem đơn hàng","status"=>"active"],
                ["alias"=>"order_delete","title"=>"Xóa đơn hàng","status"=>"active"],
                ["alias"=>"mw_add","title"=>"kho bảo hành->kho bán hàng thêm","status"=>"active"],
                ["alias"=>"mw_edit","title"=>"Điều chỉnh kho bảo hành->kho bán hàng","status"=>"active"],
                ["alias"=>"mw_list","title"=>"Xem kho bảo hành->kho bán hàng","status"=>"active"],
                ["alias"=>"mw_delete","title"=>"Xóa kho bảo hành->kho bán hàng","status"=>"active"],
                ["alias"=>"mp_add","title"=>"kho bảo hành->kho tài sản thêm","status"=>"active"],
                ["alias"=>"mp_edit","title"=>"Điều chỉnh kho bảo hành->kho tài sản","status"=>"active"],
                ["alias"=>"mp_list","title"=>"Xem kho bảo hành->kho tài sản","status"=>"active"],
                ["alias"=>"mp_delete","title"=>"Xóa kho bảo hành->kho tài sản","status"=>"active"],
                ["alias"=>"md_add","title"=>"kho bảo hành->kho hủy thêm","status"=>"active"],
                ["alias"=>"md_edit","title"=>"Điều chỉnh kho bảo hành->kho hủy","status"=>"active"],
                ["alias"=>"md_list","title"=>"Xem kho bảo hành->kho hủy","status"=>"active"],
                ["alias"=>"md_delete","title"=>"Xóa kho bảo hành->kho hủy","status"=>"active"],
                ["alias"=>"ms_add","title"=>"phiếu gửi bảo hành thêm","status"=>"active"],
                ["alias"=>"ms_edit","title"=>"Điều chỉnh phiếu gửi bảo hành","status"=>"active"],
                ["alias"=>"ms_list","title"=>"Xem phiếu gửi bảo hành","status"=>"active"],
                ["alias"=>"ms_delete","title"=>"Xóa phiếu gửi bảo hành","status"=>"active"],
                ["alias"=>"min_add","title"=>"phiếu nhận bảo hành thêm","status"=>"active"],
                ["alias"=>"min_edit","title"=>"Điều chỉnh phiếu nhận bảo hành","status"=>"active"],
                ["alias"=>"min_list","title"=>"Xem phiếu nhận bảo hành","status"=>"active"],
                ["alias"=>"min_delete","title"=>"Xóa phiếu nhận bảo hành","status"=>"active"],
                ["alias"=>"mba_add","title"=>"phiếu trả bảo hành thêm","status"=>"active"],
                ["alias"=>"mba_edit","title"=>"Điều chỉnh phiếu trả bảo hành","status"=>"active"],
                ["alias"=>"mba_list","title"=>"Xem phiếu trả bảo hành","status"=>"active"],
                ["alias"=>"mba_delete","title"=>"Xóa phiếu trả bảo hành","status"=>"active"],
                ["alias"=>"invp_list","title"=>"xem kho tài sản","status"=>"active"],
                ["alias"=>"invm_list","title"=>"xem kho bảo hành","status"=>"active"],
                ["alias"=>"invd_list","title"=>"xem kho hủy","status"=>"active"],
                ["alias"=>"inv_list","title"=>"xem kho bán hàng","status"=>"active"],
                ["alias"=>"invc_add","title"=>"kiểm kho thêm","status"=>"active"],
                ["alias"=>"invc_edit","title"=>"Điều chỉnh kiểm kho","status"=>"active"],
                ["alias"=>"invc_list","title"=>"Xem kiểm kho","status"=>"active"],
                ["alias"=>"invc_delete","title"=>"Xóa kiểm kho","status"=>"active"],
                ["alias"=>"freet_add","title"=>"loại phiếu thu chi thêm","status"=>"active"],
                ["alias"=>"freet_edit","title"=>"Điều chỉnh loại phiếu thu chi","status"=>"active"],
                ["alias"=>"freet_list","title"=>"Xem loại phiếu thu chi","status"=>"active"],
                ["alias"=>"freet_delete","title"=>"Xóa loại phiếu thu chi","status"=>"active"],
                ["alias"=>"ftrans_add","title"=>"phiếu thu chi thêm","status"=>"active"],
                ["alias"=>"ftrans_edit","title"=>"Điều chỉnh phiếu thu chi","status"=>"active"],
                ["alias"=>"ftrans_list","title"=>"Xem phiếu thu chi","status"=>"active"],
                ["alias"=>"ftrans_delete","title"=>"Xóa phiếu thu chi","status"=>"active"],
                ["alias"=>"dlv_add","title"=>"nhà vận chuyển thêm","status"=>"active"],
                ["alias"=>"dlv_edit","title"=>"Điều chỉnh nhà vận chuyển","status"=>"active"],
                ["alias"=>"dlv_list","title"=>"Xem nhà vận chuyển","status"=>"active"],
                ["alias"=>"dlv_delete","title"=>"Xóa nhà vận chuyển","status"=>"active"],
                ["alias"=>"cus_add","title"=>"khách hàng thêm","status"=>"active"],
                ["alias"=>"cus_edit","title"=>"Điều chỉnh khách hàng","status"=>"active"],
                ["alias"=>"cus_list","title"=>"Xem khách hàng","status"=>"active"],
                ["alias"=>"cus_delete","title"=>"Xóa khách hàng","status"=>"active"],
                ["alias"=>"cfunc_add","title"=>"chức năng người dùng thêm","status"=>"active"],
                ["alias"=>"cfunc_edit","title"=>"Điều chỉnh chức năng người dùng","status"=>"active"],
                ["alias"=>"cfunc_list","title"=>"Xem chức năng người dùng","status"=>"active"],
                ["alias"=>"cfunc_delete","title"=>"Xóa chức năng người dùng","status"=>"active"],
                ["alias"=>"pcat_add","title"=>"danh mục hàng hóa thêm","status"=>"active"],
                ["alias"=>"pcat_edit","title"=>"Điều chỉnh danh mục hàng hóa","status"=>"active"],
                ["alias"=>"pcat_list","title"=>"Xem danh mục hàng hóa","status"=>"active"],
                ["alias"=>"pcat_delete","title"=>"Xóa danh mục hàng hóa","status"=>"active"],
                ["alias"=>"brand_add","title"=>"nhà sản xuất thêm","status"=>"active"],
                ["alias"=>"brand_edit","title"=>"Điều chỉnh nhà sản xuất","status"=>"active"],
                ["alias"=>"brand_list","title"=>"Xem nhà sản xuất","status"=>"active"],
                ["alias"=>"brand_delete","title"=>"Xóa nhà sản xuất","status"=>"active"],
                ["alias"=>"blog_add","title"=>"bài viết thêm","status"=>"active"],
                ["alias"=>"blog_edit","title"=>"Điều chỉnh bài viết","status"=>"active"],
                ["alias"=>"blog_list","title"=>"Xem bài viết","status"=>"active"],
                ["alias"=>"blog_delete","title"=>"Xóa bài viết","status"=>"active"],
                ["alias"=>"bcat_add","title"=>"danh mục bài viết thêm","status"=>"active"],
                ["alias"=>"bcat_edit","title"=>"Điều chỉnh danh mục bài viết","status"=>"active"],
                ["alias"=>"bcat_list","title"=>"Xem danh mục bài viết","status"=>"active"],
                ["alias"=>"bcat_delete","title"=>"Xóa danh mục bài viết","status"=>"active"],
                ["alias"=>"binv_add","title"=>"tồn kho đầu kì thêm","status"=>"active"],
                ["alias"=>"binv_edit","title"=>"Điều chỉnh tồn kho đầu kì","status"=>"active"],
                ["alias"=>"binv_list","title"=>"Xem tồn kho đầu kì","status"=>"active"],
                ["alias"=>"binv_delete","title"=>"Xóa tồn kho đầu kì","status"=>"active"],
                ["alias"=>"ban_add","title"=>"banner thêm","status"=>"active"],
                ["alias"=>"ban_edit","title"=>"Điều chỉnh banner","status"=>"active"],
                ["alias"=>"ban_list","title"=>"Xem banner","status"=>"active"],
                ["alias"=>"ban_delete","title"=>"Xóa banner","status"=>"active"],
                ["alias"=>"bank_add","title"=>"tài khoản thêm","status"=>"active"],
                ["alias"=>"bank_edit","title"=>"Điều chỉnh tài khoản","status"=>"active"],
                ["alias"=>"bank_list","title"=>"Xem tài khoản","status"=>"active"],
                ["alias"=>"bank_delete","title"=>"Xóa tài khoản","status"=>"active"],
                ["alias"=>"bank_trans","title"=>"chuyển tiền tài khoản","status"=>"active"],
                ["alias"=>"role_add","title"=>"tài khoản thêm","status"=>"active"],
                ["alias"=>"role_edit","title"=>"Điều chỉnh tài khoản","status"=>"active"],
                ["alias"=>"role_list","title"=>"Xem tài khoản","status"=>"active"],
                ["alias"=>"role_delete","title"=>"Xóa tài khoản","status"=>"active"],
                ["alias"=>"role_function","title"=>"Phân quyền cho vai trò","status"=>"active"],
                ["alias"=>"site_setting","title"=>"cài đặt thông tin website","status"=>"active"],
                ["alias"=>"sup_add","title"=>"nhà cung cấp thêm","status"=>"active"],
                ["alias"=>"sup_edit","title"=>"Điều chỉnh nhà cung cấp","status"=>"active"],
                ["alias"=>"sup_list","title"=>"Xem nhà cung cấp","status"=>"active"],
                ["alias"=>"sup_delete","title"=>"Xóa nhà cung cấp","status"=>"active"],
                ["alias"=>"warh_add","title"=>"kho hàng thêm","status"=>"active"],
                ["alias"=>"warh_edit","title"=>"Điều chỉnh kho hàng","status"=>"active"],
                ["alias"=>"warh_list","title"=>"Xem kho hàng","status"=>"active"],
                ["alias"=>"warh_delete","title"=>"Xóa kho hàng","status"=>"active"],
                ["alias"=>"warin_add","title"=>"nhập kho thêm","status"=>"active"],
                ["alias"=>"warin_edit","title"=>"Điều chỉnh nhập kho","status"=>"active"],
                ["alias"=>"warin_list","title"=>"Xem nhập kho","status"=>"active"],
                ["alias"=>"warin_delete","title"=>"Xóa nhập kho","status"=>"active"],
                ["alias"=>"warin_return","title"=>"trả hàng nhập kho","status"=>"active"],
                ["alias"=>"warout_add","title"=>"xuất kho bán hàng thêm","status"=>"active"],
                ["alias"=>"warout_edit","title"=>"Điều chỉnh xuất kho bán hàng","status"=>"active"],
                ["alias"=>"warout_list","title"=>"Xem xuất kho bán hàng","status"=>"active"],
                ["alias"=>"warout_delete","title"=>"Xóa xuất kho bán hàng","status"=>"active"],
                ["alias"=>"warout_return","title"=>"trả hàng xuất kho bán hàng","status"=>"active"],
                ["alias"=>"wd_add","title"=>"kho bán hàng->kho hủy thêm","status"=>"active"],
                ["alias"=>"wd_edit","title"=>"Điều chỉnh kho bán hàng->kho hủy","status"=>"active"],
                ["alias"=>"wd_list","title"=>"Xem kho bán hàng->kho hủy","status"=>"active"],
                ["alias"=>"wd_delete","title"=>"Xóa kho bán hàng->kho hủy","status"=>"active"],
                ["alias"=>"wm_add","title"=>"kho bán hàng->kho bảo hành thêm","status"=>"active"],
                ["alias"=>"wm_edit","title"=>"Điều chỉnh kho bán hàng->kho bảo hành","status"=>"active"],
                ["alias"=>"wm_list","title"=>"Xem kho bán hàng->kho bảo hành","status"=>"active"],
                ["alias"=>"wm_delete","title"=>"Xóa kho bán hàng->kho bảo hành","status"=>"active"],
                ["alias"=>"wp_add","title"=>"kho bán hàng->kho tài sản thêm","status"=>"active"],
                ["alias"=>"wp_edit","title"=>"Điều chỉnh kho bán hàng->kho tài sản","status"=>"active"],
                ["alias"=>"wp_list","title"=>"Xem kho bán hàng->kho tài sản","status"=>"active"],
                ["alias"=>"wp_delete","title"=>"Xóa kho bán hàng->kho tài sản","status"=>"active"],
                ["alias"=>"wht_add","title"=>"chuyển kho bán hàng thêm","status"=>"active"],
                ["alias"=>"wht_edit","title"=>"Điều chỉnh chuyển kho bán hàng","status"=>"active"],
                ["alias"=>"wht_list","title"=>"Xem chuyển kho bán hàng","status"=>"active"],
                ["alias"=>"wht_delete","title"=>"Xóa chuyển kho bán hàng","status"=>"active"],
                ["alias"=>"admin_view","title"=>"admin_view","status"=>"active"],
                ["alias"=>"report_list","title"=>"report_list","status"=>"active"],
                ["alias"=>"invoice_read","title"=>"invoice_read","status"=>"active"],
            ]
        );


    }
}
